plugins {
    id 'com.android.application'
}

android {
    namespace 'com.karimmnagy.aiassistant'
    compileSdk 35

    defaultConfig {
        applicationId 'com.karimmnagy.aiassistant'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildFeatures {
        buildConfig true
    }
}
